import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const colors=["#2563eb","#22c55e","#f59e0b","#ef4444","#7c3aed","#06b6d4"];

export function IncidentAreaChart({data=[]}){if(!data.length)return <Empty/>;return <ResponsiveContainer width="100%" height={260}><AreaChart data={data} margin={{top:10,right:14,left:-18,bottom:0}}><defs><linearGradient id="incidentFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2563eb" stopOpacity={0.38}/><stop offset="95%" stopColor="#2563eb" stopOpacity={0.03}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="period" tick={{fontSize:11}}/><YAxis allowDecimals={false} tick={{fontSize:11}}/><Tooltip/><Area type="monotone" dataKey="count" name="Incidents" stroke="#2563eb" strokeWidth={3} fill="url(#incidentFill)"/></AreaChart></ResponsiveContainer>}
export function CategoryDonut({data=[]}){if(!data.length)return <Empty/>;return <ResponsiveContainer width="100%" height={260}><PieChart><Pie data={data} dataKey="count" nameKey="category" innerRadius={58} outerRadius={92} paddingAngle={3}>{data.map((entry,index)=><Cell key={entry.category} fill={colors[index%colors.length]}/>)}</Pie><Tooltip/><Legend verticalAlign="bottom" height={28}/></PieChart></ResponsiveContainer>}
export function HealthBarChart({data=[]}){return <ResponsiveContainer width="100%" height={260}><BarChart data={data} layout="vertical" margin={{top:10,right:18,left:20,bottom:0}}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis type="number" domain={[0,100]} tick={{fontSize:11}}/><YAxis type="category" dataKey="label" width={90} tick={{fontSize:11}}/><Tooltip formatter={(value)=>`${value}%`}/><Bar dataKey="value" name="Health" fill="#22c55e" radius={[0,7,7,0]}/></BarChart></ResponsiveContainer>}
function Empty(){return <div className="flex h-64 items-center justify-center text-sm font-semibold text-slate-400">No chart data available.</div>}

export function IncidentHeatmap({data=[]}){const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];const max=Math.max(1,...data.map(item=>Number(item.count)));const lookup=new Map(data.map(item=>[`${item.day_index}-${item.hour_index}`,Number(item.count)]));return <div className="overflow-x-auto pt-5"><div className="min-w-[620px]"><div className="ml-12 grid grid-cols-12 gap-1 text-center text-[9px] font-bold text-slate-400">{Array.from({length:12},(_,i)=><span key={i}>{String(i*2).padStart(2,"0")}</span>)}</div><div className="mt-2 space-y-1">{days.map((day,dayIndex)=><div key={day} className="flex items-center gap-2"><span className="w-10 text-[10px] font-bold text-slate-500">{day}</span><div className="grid flex-1 gap-1" style={{gridTemplateColumns:"repeat(24,minmax(0,1fr))"}}>{Array.from({length:24},(_,hour)=>{const value=lookup.get(`${dayIndex+1}-${hour}`)||0;const opacity=value?0.15+value/max*0.85:0.05;return <div key={hour} title={`${day} ${String(hour).padStart(2,"0")}:00 · ${value} incidents`} className="h-5 rounded-sm bg-blue-600 transition hover:scale-125 hover:ring-2 hover:ring-blue-300" style={{opacity}}/>})}</div></div>)}</div></div></div>}
