-- Establish the asset table before financial and discovery migrations extend it.
CREATE TABLE IF NOT EXISTS hardware_assets (
  asset_id SERIAL PRIMARY KEY,
  asset_name VARCHAR(255) NOT NULL,
  asset_type VARCHAR(100) NOT NULL,
  brand VARCHAR(100),
  manufacturer VARCHAR(100),
  model VARCHAR(150),
  serial_number VARCHAR(150) NOT NULL UNIQUE,
  asset_tag VARCHAR(150) UNIQUE,
  color VARCHAR(100),
  purchase_price NUMERIC(12,2),
  supplier VARCHAR(150),
  assigned_name VARCHAR(255),
  returned_name VARCHAR(255),
  warranty VARCHAR(100),
  condition_notes TEXT,
  team_department VARCHAR(100),
  assigned_date DATE,
  returned_date DATE,
  accessories TEXT,
  processor VARCHAR(150),
  ram VARCHAR(100),
  storage VARCHAR(150),
  signature_link TEXT,
  returned_name_forms VARCHAR(255),
  attachments JSONB,
  image_url TEXT,
  branch_id INTEGER REFERENCES branches(branch_id),
  status VARCHAR(50) NOT NULL DEFAULT 'Active',
  purchase_date DATE,
  warranty_expiration DATE,
  borrower_name VARCHAR(150),
  borrower_email VARCHAR(255),
  employee_id VARCHAR(100),
  borrower_department VARCHAR(100),
  borrow_date DATE,
  expected_return_date DATE,
  actual_return_date DATE,
  condition_before TEXT,
  condition_after TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
