import { lazy, Suspense, useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { AlertCircle, AlertTriangle, BarChart3, CheckCircle2, FileText, Folder, HeartPulse, RefreshCw } from "lucide-react";
import PageHero from "../components/layout/PageHero";
import { API_URL } from "../config/api";
import { authHeaders } from "../services/authHeaders";

const chartModule = () => import("../components/ProjectAnalyticsCharts");
const MilestoneChart = lazy(() => chartModule().then((module) => ({ default: module.MilestoneChart })));
const CostChart = lazy(() => chartModule().then((module) => ({ default: module.CostChart })));
const ResourceChart = lazy(() => chartModule().then((module) => ({ default: module.ResourceChart })));
const ForecastChart = lazy(() => chartModule().then((module) => ({ default: module.ForecastChart })));
const ProblemTrendChart = lazy(() => chartModule().then((module) => ({ default: module.ProblemTrendChart })));
const API_ENDPOINT = `${API_URL}/api/v1/projects/dashboard`;

function Card({ children, className = "" }) {
  return <section className={`rounded-2xl border border-slate-100 bg-white p-5 shadow-sm ${className}`}>{children}</section>;
}
function CardTitle({ title, subtitle }) {
  return <div><h2 className="text-base font-black text-slate-900">{title}</h2>{subtitle && <p className="mt-1 text-xs text-slate-400">{subtitle}</p>}</div>;
}
function KpiCard({ icon: Icon, label, value, detail, accent, badge }) {
  return <Card><div className="flex items-start justify-between gap-3"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${accent}`}><Icon size={21}/></div>{badge && <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide ${badge}`}>Portfolio</span>}</div><p className="mt-4 text-2xl font-black text-slate-900">{value}</p><p className="mt-1 text-sm font-bold text-slate-700">{label}</p><p className="mt-0.5 text-xs text-slate-400">{detail}</p></Card>;
}

function Skeleton() {
  return <div className="animate-pulse space-y-5"><div className="grid grid-cols-2 gap-4 xl:grid-cols-5">{Array.from({length:5},(_,i)=><div key={i} className="h-40 rounded-2xl bg-slate-100"/>)}</div><div className="grid gap-4 lg:grid-cols-3">{Array.from({length:3},(_,i)=><div key={i} className="h-80 rounded-2xl bg-slate-100"/>)}</div></div>;
}

function ScheduleCard({ projects }) {
  return <Card><CardTitle title="Schedule & Progress" subtitle="Planned versus actual completion"/><div className="mt-5 space-y-4">{projects.length ? projects.slice(0,6).map((project)=><div key={project.project_id} title={`${project.project_name}: planned ${project.planned_completion_pct}%, actual ${project.actual_completion_pct}%`}><div className="flex items-center justify-between gap-3"><p className="truncate text-xs font-bold text-slate-700">{project.project_name}</p><span className="text-xs font-black text-blue-700">{project.actual_completion_pct}%</span></div><div className="mt-2 space-y-1"><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-300" style={{width:`${Math.min(project.planned_completion_pct,100)}%`}}/></div><div className="h-2 overflow-hidden rounded-full bg-blue-50"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.min(project.actual_completion_pct,100)}%`}}/></div></div></div>):<p className="py-16 text-center text-sm font-semibold text-slate-400">No active projects available.</p>}</div><div className="mt-5 flex gap-5 border-t border-slate-100 pt-4 text-xs font-bold text-slate-500"><span><i className="mr-2 inline-block h-2 w-5 rounded bg-slate-300"/>Planned</span><span><i className="mr-2 inline-block h-2 w-5 rounded bg-blue-600"/>Actual</span></div></Card>;
}

export default function AdvancedProjectDashboard() {
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(API_ENDPOINT,{headers:authHeaders()});const result=await response.json();if(!response.ok)throw new Error(result.message||"Failed to load project analytics.");setData(result.data);}catch(err){setError(err.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const projected=useMemo(()=>data?.forecast?.filter((item)=>item.projected_finish_date).sort((a,b)=>new Date(a.projected_finish_date)-new Date(b.projected_finish_date))[0]||null,[data]);
  if(loading)return <div className="space-y-6"><PageHero eyebrow="Project Analytics" title="Project Dashboard" subtitle="Monitor IT project execution, risks, earned value, resources, and forecast completion."/><Skeleton/></div>;
  if(error)return <div className="space-y-6"><PageHero eyebrow="Project Analytics" title="Project Dashboard" subtitle="Monitor IT project execution, risks, earned value, resources, and forecast completion."/><Card className="text-center"><AlertCircle className="mx-auto text-red-500"/><p className="mt-3 font-bold text-slate-800">{error}</p><button onClick={load} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white"><RefreshCw className="mr-2 inline" size={15}/>Retry</button></Card></div>;
  const p=data.portfolio;
  return <div className="space-y-6"><PageHero eyebrow="Project Analytics" title="Project Dashboard" subtitle="Monitor IT project execution, risks, earned value, resources, and forecast completion." actions={<button onClick={load} className="rounded-xl border border-white/30 bg-white/10 px-4 py-2 text-sm font-bold text-white hover:bg-white/20"><RefreshCw className="mr-2 inline" size={15}/>Refresh</button>}/>
    <div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-5"><KpiCard icon={Folder} label="Total Projects" value={p.total_projects} detail="Total active projects" accent="bg-blue-50 text-blue-600"/><KpiCard icon={CheckCircle2} label="Projects On Track" value={`${p.on_track_pct}%`} detail="Healthy execution" accent="bg-emerald-50 text-emerald-600" badge="bg-emerald-50 text-emerald-700"/><KpiCard icon={AlertTriangle} label="Projects At Risk" value={`${p.at_risk_pct}%`} detail="Requires attention" accent="bg-amber-50 text-amber-600" badge="bg-amber-50 text-amber-700"/><KpiCard icon={AlertCircle} label="Projects Delayed" value={`${p.delayed_pct}%`} detail="Behind schedule" accent="bg-red-50 text-red-600" badge="bg-red-50 text-red-700"/><KpiCard icon={HeartPulse} label="Portfolio Health Score" value={`${p.health_score.toFixed(1)} / 10`} detail="Average project health" accent="bg-indigo-50 text-indigo-600"/></div>
    <Suspense fallback={<Skeleton/>}><div className="grid gap-4 lg:grid-cols-3"><ScheduleCard projects={data.schedule}/><Card><CardTitle title="Milestone Completion" subtitle="Delivery checkpoint performance"/><MilestoneChart data={data.milestones}/><div className="grid grid-cols-3 gap-2 text-center"><div><p className="font-black text-slate-900">{data.milestones.completed}</p><p className="text-[10px] font-bold text-slate-400">Completed</p></div><div><p className="font-black text-slate-900">{data.milestones.remaining}</p><p className="text-[10px] font-bold text-slate-400">Remaining</p></div><div><p className="font-black text-slate-900">{data.milestones.upcoming}</p><p className="text-[10px] font-bold text-slate-400">Upcoming</p></div></div></Card><Card><CardTitle title="Risk & Issue Summary" subtitle="Open portfolio exposure"/><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-4"><AlertCircle className="text-blue-600" size={20}/><p className="mt-3 text-2xl font-black text-slate-900">{data.risks.open_issues}</p><p className="text-xs font-bold text-slate-500">Open Issues</p></div><div className="rounded-xl bg-red-50 p-4"><AlertTriangle className="text-red-600" size={20}/><p className="mt-3 text-2xl font-black text-slate-900">{data.risks.high_risk_issues}</p><p className="text-xs font-bold text-slate-500">High Risk</p></div></div><div className="mt-6 space-y-2 text-xs font-semibold text-slate-500"><p><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full bg-red-500"/>High and critical exposure</p><p><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full bg-blue-500"/>All unresolved issues</p></div></Card></div>
    <div className="grid gap-4 lg:grid-cols-3"><Card><CardTitle title="Project Cost & Earned Value" subtitle="PV, EV, and AC portfolio comparison"/><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><p>PV <b className="block text-slate-900">₱{Math.round(data.costs.planned_value).toLocaleString()}</b></p><p>EV <b className="block text-blue-700">₱{Math.round(data.costs.earned_value).toLocaleString()}</b></p><p>AC <b className="block text-amber-700">₱{Math.round(data.costs.actual_cost).toLocaleString()}</b></p></div><CostChart data={data.costs}/></Card><Card><CardTitle title="Resource Utilization" subtitle="Allocated versus available capacity"/><ResourceChart data={data.resources}/><div className="grid grid-cols-2 text-center text-xs"><p>Allocated <b className="block text-slate-900">{data.resources.allocated}%</b></p><p>Available <b className="block text-slate-900">{data.resources.available}%</b></p></div></Card><Card><CardTitle title="Forecast & Insights" subtitle="Completion outlook and confidence"/><ForecastChart data={data.forecast}/><div className="mt-3 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-xs"><p className="text-slate-500">Projected Finish<b className="block text-slate-900">{projected?.projected_finish_date||"Not available"}</b></p><p className="text-slate-500">Confidence<b className="block text-slate-900">{projected?`${projected.confidence}%`:"Not available"}</b></p></div></Card></div>
    <div className="grid gap-4 lg:grid-cols-3"><Card><CardTitle title="Problem Management Integration" subtitle="Existing Service Desk problem intelligence"/><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-blue-50 p-4"><p className="text-2xl font-black text-blue-700">{data.problems.recurring_problems.length}</p><p className="text-xs font-bold text-slate-600">Recurring Problems</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-2xl font-black text-amber-700">{data.problems.known_errors}</p><p className="text-xs font-bold text-slate-600">Known Errors</p></div></div></Card><Card><CardTitle title="Root Cause Categories" subtitle="Categories with documented root causes"/><div className="mt-5 space-y-3">{data.problems.root_cause_categories.length?data.problems.root_cause_categories.map((item)=><div key={item.category} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm"><span className="font-bold text-slate-700">{item.category}</span><span className="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-black text-blue-700">{item.count}</span></div>):<p className="py-8 text-center text-sm font-semibold text-slate-400">No root-cause data available.</p>}</div></Card><Card><CardTitle title="Problem Trends" subtitle="Six-month incident trend"/><ProblemTrendChart data={data.problems.trends}/></Card></div></Suspense>
    <Card><div className="flex items-center gap-3"><BarChart3 className="text-blue-600"/><CardTitle title="Reporting Quick Links" subtitle="Continue into existing AstreaBlue reporting modules"/></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5">{[["Executive Reports","/analytics"],["Project Reports","/custom-reports"],["Risk Reports","/trend-analysis"],["Resource Reports","/custom-reports"],["Custom Reports","/custom-reports"]].map(([label,path])=><Link key={label} to={path} className="flex items-center gap-2 rounded-xl border border-slate-100 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-700 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700"><FileText size={16}/>{label}</Link>)}</div></Card>
  </div>;
}


