import { useCallback, useEffect, useMemo, useState } from "react";
import { Link2, Plus, Radar, Upload, X } from "lucide-react";
import PageHero from "../components/layout/PageHero";
import { API_URL } from "../config/api";

const API_BASE = `${API_URL}/api/v1`;
const empty = { hostname:"",ip_address:"",mac_address:"",serial_number:"",asset_tag:"",os_name:"",manufacturer:"",device_type:"",status:"Online",branch_id:"" };

export default function AssetDiscovery() {
  const [records,setRecords]=useState([]); const [assets,setAssets]=useState([]); const [branches,setBranches]=useState([]);
  const [history,setHistory]=useState([]);
  const [showManual,setShowManual]=useState(false); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{try{setLoading(true);const [d,h,a,b]=await Promise.all([fetch(`${API_BASE}/hardware-assets/discovery`),fetch(`${API_BASE}/hardware-assets/discovery/history`),fetch(`${API_BASE}/hardware-assets`),fetch(`${API_BASE}/branches`)]);const [db,hb,ab,bb]=await Promise.all([d.json(),h.json(),a.json(),b.json()]);if(!d.ok||db.success===false)throw new Error(db.message||db.error);if(!h.ok||hb.success===false)throw new Error(hb.message||hb.error);setRecords(db.data||[]);setHistory(hb.data||[]);setAssets(Array.isArray(ab)?ab:[]);setBranches(Array.isArray(bb)?bb:[]);}catch(e){setMessage(e.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{const refresh=()=>load();window.addEventListener("astreablue:refresh-dashboard",refresh);return()=>window.removeEventListener("astreablue:refresh-dashboard",refresh);},[load]);
  const metrics=useMemo(()=>({matched:records.filter(r=>r.reconciliation_status==="Matched").length,unmanaged:records.filter(r=>r.reconciliation_status==="Unmanaged").length,offline:records.filter(r=>r.status==="Offline"||r.reconciliation_status==="Offline").length,duplicate:records.filter(r=>r.reconciliation_status==="Duplicate").length}),[records]);
  const scan=async()=>{const res=await fetch(`${API_BASE}/hardware-assets/discovery/scan`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const body=await res.json();setMessage(body.message||body.error);if(body.data?.mode==="agent-required")setShowManual(true);};
  const link=async(id,assetId)=>{if(!assetId)return;const res=await fetch(`${API_BASE}/hardware-assets/discovery/${id}/link`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({asset_id:Number(assetId)})});const body=await res.json();setMessage(body.message||body.error);if(res.ok)load();};
  const createAsset=async(id,branchId)=>{const res=await fetch(`${API_BASE}/hardware-assets/discovery/${id}/create-asset`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:branchId||null})});const body=await res.json();setMessage(body.message||body.error);if(res.ok)load();};
  const importCsv=async(file)=>{if(!file)return;const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);const headers=lines.shift()?.split(",").map(v=>v.trim())||[];const imported=lines.map(line=>Object.fromEntries(line.split(",").map((value,index)=>[headers[index],value.trim()])));const res=await fetch(`${API_BASE}/hardware-assets/discovery/import`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({records:imported})});const body=await res.json();setMessage(body.message||body.error);if(res.ok)load();};
  return <div className="space-y-6"><PageHero eyebrow="Asset Discovery" title="Asset Discovery & Inventory" subtitle="Register observed devices, reconcile them with managed hardware, and prepare agent-based network discovery." actions={<><button onClick={scan} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 font-black text-blue-700"><Radar size={17}/> Scan Network</button><button onClick={()=>setShowManual(true)} className="inline-flex items-center gap-2 rounded-xl bg-cyan-100 px-4 py-3 font-black text-blue-900"><Plus size={17}/> Manual Registration</button><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-white/10 px-4 py-3 font-black text-white"><Upload size={17}/> Import CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={(e)=>importCsv(e.target.files?.[0])}/></label></>} />
    {message&&<div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 font-semibold text-blue-800">{message}</div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-4 text-sm text-slate-600 shadow-sm"><span className="font-black text-slate-900">Last scan or import:</span> {history[0] ? `${new Date(history[0].started_at).toLocaleString()} · ${history[0].source || history[0].status}` : "No scan or import has been recorded yet."}</section>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Matched",metrics.matched],["Unmanaged",metrics.unmanaged],["Offline",metrics.offline],["Duplicates",metrics.duplicate]].map(([label,value])=><div key={label} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-slate-900">{value}</p></div>)}</section>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Device","Network","Identity","OS / Manufacturer","Source","Last Seen","Status","Reconciliation","Actions"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="9" className="p-8 text-center">Loading discovery registry...</td></tr>:records.map(r=><DiscoveryRow key={r.discovery_id} record={r} assets={assets} branches={branches} onLink={link} onCreate={createAsset}/>)}</tbody></table></div></section>
    {showManual&&<ManualModal branches={branches} onClose={()=>setShowManual(false)} onSaved={(text)=>{setShowManual(false);setMessage(text);load();}}/>}
  </div>;
}

function DiscoveryRow({record,assets,branches,onLink,onCreate}){const [assetId,setAssetId]=useState("");return <tr className="border-t border-slate-100"><td className="px-4 py-4"><p className="font-black">{record.hostname}</p><p className="text-xs text-slate-500">{record.device_type||"Unknown device"}</p></td><td className="px-4 py-4 text-sm">{record.ip_address||"—"}<br/>{record.mac_address||"—"}</td><td className="px-4 py-4 text-sm">{record.serial_number||record.asset_tag||"—"}</td><td className="px-4 py-4 text-sm">{record.os_name||"—"}<br/>{record.manufacturer||"—"}</td><td className="px-4 py-4">{record.source}</td><td className="px-4 py-4 text-sm">{new Date(record.last_seen).toLocaleString()}</td><td className="px-4 py-4">{record.status}</td><td className="px-4 py-4 font-bold">{record.reconciliation_status}</td><td className="px-4 py-4">{record.matched_asset_id?<span className="font-bold text-emerald-700">{record.matched_asset_tag||"Matched"}</span>:<div className="flex gap-2"><select value={assetId} onChange={e=>setAssetId(e.target.value)} className="max-w-40 rounded-lg border px-2 py-1"><option value="">Select asset</option>{assets.map(a=><option key={a.asset_id} value={a.asset_id}>{a.asset_tag}</option>)}</select><button onClick={()=>onLink(record.discovery_id,assetId)} className="rounded-lg bg-blue-50 p-2 text-blue-700"><Link2 size={14}/></button><button onClick={()=>onCreate(record.discovery_id,record.branch_id||branches[0]?.branch_id)} className="rounded-lg bg-emerald-50 px-2 text-xs font-bold text-emerald-700">Create Asset</button></div>}</td></tr>}

function ManualModal({branches,onClose,onSaved}){const [form,setForm]=useState(empty);const [error,setError]=useState("");const save=async(e)=>{e.preventDefault();const res=await fetch(`${API_BASE}/hardware-assets/discovery`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await res.json();if(!res.ok||body.success===false)return setError(body.message||body.error);onSaved(body.message);};return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><form onSubmit={save} className="w-full max-w-2xl rounded-3xl border border-slate-200 bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-black">Manual Discovery</h2><p className="text-sm text-slate-500">Register a real observed device for reconciliation.</p></div><button type="button" onClick={onClose}><X/></button></div>{error&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2">{[["Hostname","hostname"],["IP Address","ip_address"],["MAC Address","mac_address"],["Serial Number","serial_number"],["Asset Tag","asset_tag"],["Operating System","os_name"],["Manufacturer","manufacturer"],["Device Type","device_type"]].map(([label,key])=><label key={key} className="text-sm font-bold">{label}<input required={key==="hostname"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2"/></label>)}<label className="text-sm font-bold">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2"><option>Online</option><option>Offline</option></select></label><label className="text-sm font-bold">Branch<select value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})} className="mt-2 w-full rounded-xl border px-3 py-2"><option value="">Select branch</option>{branches.map(b=><option key={b.branch_id} value={b.branch_id}>{b.branch_name}</option>)}</select></label></div><button className="mt-6 w-full rounded-xl bg-blue-700 px-4 py-3 font-black text-white">Register Discovery</button></form></div>}
